### ISSUE TITLE
Copy changes from W3 to W2

### ISSUE THREAD

**Issue by jaros1** [jaros1/Money-Network-W2#61]
Many minor errors from W2 has been fixed in W3

**Comment by jaros1** [comment]
todo: 
- test w3 backup and restore. Should work. code identical with w2.
- confirm send money transaction. test confirm dialog in mn and w2 for send and request money
- confirm receive money transaction. test confirm dialog in mn and w2 for send and receive money

**Comment by jaros1** [comment]
Test 1. Send money from torando to arch linux. confirm enabled in both wallets. failed with p­r­e­p­a­r­e­_­m­t­_­r­e­q­u­e­s­t­ ­r­e­q­u­e­s­t­ ­f­a­i­l­e­d­ ­w­i­t­h­ ­J­S­ ­e­r­r­o­r­ ­s­e­s­s­i­o­n­_­i­n­f­o­ ­i­s­ ­n­o­t­ ­d­e­f­i­n­e­d

[127.0.0.1-1524579997735.log](https://github.com/jaros1/Money-Network-W2/files/1943161/127.0.0.1-1524579997735.log)

16:26:21.237 all.js:140196 MoneyNetworkW2Service.process_incoming_message.prepare_mt_request/739:  ReferenceError: session_info is not defined
    at step_1_confirm (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js.zip/all.js:140466:87)
    at prepare_mt_request (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js.zip/all.js:140508:33)
    at process_incoming_message (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js.zip/all.js:140511:27)
    at step_4_run_cb (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:1070:27)
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:1079:25
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4856:18
    at MoneyNetworkAPI.decrypt_1 (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4659:5)
    at MoneyNetworkAPI.decrypt_json (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4842:14)
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4873:62
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4750:13

**Comment by jaros1** [comment]
Test 2. Fixed error in test 1. OK confirm send money confirm box.
![screenshot from 2018-04-24 16-34-44](https://user-images.githubusercontent.com/4932088/39194270-9cc8c002-47dd-11e8-940d-d1d164840c2a.png)

Approve incoming money transaction in arch linux failed with: c­h­e­c­k­_­m­t­ ­r­e­q­u­e­s­t­ ­f­a­i­l­e­d­ ­w­i­t­h­ ­J­S­ ­e­r­r­o­r­ ­s­t­e­p­_­2­_­o­p­e­n­_­w­a­l­l­e­t­ ­i­s­ ­n­o­t­ ­d­e­f­i­n­e­d.
[192.168.0.53-1524580676484.log](https://github.com/jaros1/Money-Network-W2/files/1943227/192.168.0.53-1524580676484.log)

16:36:52.261 all.js:140196 MoneyNetworkW2Service.process_incoming_message.check_mt.step_1_confirm send_message callback 1/80:  ReferenceError: step_2_open_wallet is not defined
    at http://192.168.0.53:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js.zip/all.js:140991:49
    at http://192.168.0.53:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:5474:57
    at http://192.168.0.53:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4856:18
    at MoneyNetworkAPI.decrypt_1 (http://192.168.0.53:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4659:5)
    at MoneyNetworkAPI.decrypt_json (http://192.168.0.53:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4842:14)
    at http://192.168.0.53:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4873:62
    at http://192.168.0.53:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4750:13
    at ZeroFrame.onMessage (http://192.168.0.53:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js.zip/all.js:27018:17)
    at http://192.168.0.53:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js.zip/all.js:26982:59

**Comment by jaros1** [comment]
Test 3. fixed error in test 2. OK confirm receive money in arch linux

![screenshot from 2018-04-24 16-45-01](https://user-images.githubusercontent.com/4932088/39194928-007623a0-47df-11e8-8e8a-071a66d7b627.png)

Send money error in torando. Must be a message from btc.com

![screenshot from 2018-04-24 16-48-42](https://user-images.githubusercontent.com/4932088/39195353-f5099988-47df-11e8-9460-7718d7037f24.png)

[127.0.0.1-1524581384703.log](https://github.com/jaros1/Money-Network-W2/files/1943314/127.0.0.1-1524581384703.log)

**Comment by jaros1** [comment]
Test 4. Sending money direct from W2 with debug. 

base_fee is no longer supported. Changed to optimal
                    // bitcoin_wallet.pay(payment, null, false, true, blocktrail.Wallet.FEE_STRATEGY_BASE_FEE, cb) ;
                    bitcoin_wallet.pay(payment, null, false, true, blocktrail.Wallet.FEE_STRATEGY_OPTIMAL, cb) ;

Optimal: The middle ground, where you pay a higher fee than in the “Low” category but you can expect a shorter confirmation time.

**Comment by jaros1** [comment]
Test 5. send money from torando to arch linux. Money was sent from torando to arch linux, but arch linux cannot verify transaction. Origin is not allowed by Access-Control-Allow-Origin. Tried with and without vpn.

![screenshot from 2018-04-24 17-39-33](https://user-images.githubusercontent.com/4932088/39198121-8a795cdc-47e6-11e8-87e1-a3b5e451fbbb.png)

[192.168.0.53-1524584421875.log](https://github.com/jaros1/Money-Network-W2/files/1943518/192.168.0.53-1524584421875.log)

OK after disabling both torando and arch linux vpn connections ...
![screenshot from 2018-04-24 17-42-06](https://user-images.githubusercontent.com/4932088/39198274-f1ef5baa-47e6-11e8-98a3-1501ce5551e8.png)

**Comment by jaros1** [comment]
Test 6: request money from arch linux
OK request money confirm dialog in torando.
OK send money confirm dialog in arch linux.
Test OK. Had to disable vpn in torando to verify incoming money transactionid.

**Comment by jaros1** [comment]
Test 7. torando: send and request money to/from arch linux
JS error in torando: p­r­e­p­a­r­e­_­m­t­_­r­e­q­u­e­s­t­ ­r­e­q­u­e­s­t­ ­f­a­i­l­e­d­ ­w­i­t­h­ ­J­S­ ­e­r­r­o­r­ ­s­e­s­s­i­o­n­_­i­n­f­o­ ­i­s­ ­n­o­t­ ­d­e­f­i­n­e­d
[127.0.0.1-1524585143362.log](https://github.com/jaros1/Money-Network-W2/files/1943558/127.0.0.1-1524585143362.log)

all.js:140197 MoneyNetworkW2Service.process_incoming_message.prepare_mt_request/1749:  ReferenceError: session_info is not defined
    at step_1_confirm (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js.zip/all.js:140466:108)
    at prepare_mt_request (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js.zip/all.js:140509:33)
    at process_incoming_message (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js/all.js.zip/all.js:140512:27)
    at step_4_run_cb (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:1070:27)
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:1079:25
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4856:18
    at MoneyNetworkAPI.decrypt_1 (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4659:5)
    at MoneyNetworkAPI.decrypt_json (http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4842:14)
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4873:62
    at http://127.0.0.1:43110/1LqUnXPEgcS15UGwEgkbuTbKYZqAUwQ7L1/js-api/MoneyNetworkAPI.js:4750:13

**Comment by jaros1** [comment]
Test 7 continued. Fixed JS error. torando: send and request money to/from arch linux
Minor bug in send transaction confirm dialog in torando:

![screenshot from 2018-04-24 17-57-52](https://user-images.githubusercontent.com/4932088/39199189-2576bb06-47e9-11e8-90c2-260ab844f40a.png)

**Comment by jaros1** [comment]
Test 7 continued
OK send money transaction confirm box in torando.
Same error in receive transaction confirm box in arch linux.

![screenshot from 2018-04-24 18-05-15](https://user-images.githubusercontent.com/4932088/39199613-3110e3dc-47ea-11e8-9a5e-941f2fce88f8.png)

**Comment by jaros1** [comment]
Test 7 continue. Approved incoming money transaction in arch linux. OK confirm box.
Hanging money transaction after first send notification in torando: 0.00006107 tBTC / 6107 test satoshi
was sent to arch linux.
reloaded both w2 sessions to restart transaction processing
Has to disable vpn for btc transaction verification + manual update w2 wallet data hubs.
[arch-linux-192.168.0.53-1524587055297.log](https://github.com/jaros1/Money-Network-W2/files/1943705/arch-linux-192.168.0.53-1524587055297.log)
[Uploading torando-127.0.0.1-1524587042864.log…]()
